language: java
jdk:
  - openjdk11

services:
  - docker

install:
  - mvn install -DskipTests

before_script:
  - docker ps -a -q
  - docker build serveur -t exempleio:serveur
  - docker build client -t exempleio:client
  - docker images

script:
  - mvn test
#  - docker-compose run serveur
# on lance 3 clients, dont 2 qui ne pourront se connecter...
  - docker-compoer up --scale client=3
  - docker-compose logs
#  on efface tous les containers éteints puis les images)
  - docker rm $(docker ps -a -q)
  - docker ps -a -q
  - docker rmi exempleio:serveur
  - docker rmi exempleio:client
