language: java
jdk:
  - openjdk11

services:
  - docker

install:
  - mvn install -DskipTests

before_script:
  - docker ps -a -q
  - docker build serveur -t exempleio:serveur
  - docker build client -t exempleio:client
  - docker images

script:
  - mvn test
  - docker-compose run serveur
#  - docker run -d  -p 10101:10101 --name serveurio  exempleio:serveur
#  - cd client
#  - mvn exec:java
# on efface à la fin le container et le l'image docker
#  - docker stop serveurio
#  - docker rm serveurio
#  - docker rmi exempleio:serveur
  - docker rm $(docker ps -a -q)
  - docker ps -a -q
  - docker rmi exempleio:serveur
  - docker rmi exempleio:client
