version: '3'

services:


  serveur:
    image: exempleio:serveur
    container_name: serveur
    networks:
      testing_net:
        ipv4_address: 172.28.0.253
    depends_on:
      - client

  client:
    image: exempleio:client
    # container_name: client
    networks:
      testing_net:
      #  ipv4_address: 172.28.0.3




networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
