version: '3'

services:

  client:
    image: exempleio:client
    container_name: client
    networks:
      testing_net:
        ipv4_address: 172.28.0.3


  serveur:
    image: exempleio:serveur
    container_name: serveur
    networks:
      testing_net:
        ipv4_address: 172.28.0.2
    depends_on:
      - client



networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
